apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-test-cluster
  namespace: kafka-test
spec:
  kafka:
    version: 2.2.1
    replicas: 3
    listeners:
      external:
        type: route
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.2'
    storage:
      type: persistent-claim
      size: 1Gi
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}  